// flow-typed signature: 4f2b61a861c650a9ddbb3dc6aae145a9
// flow-typed version: <<STUB>>/awilix-koa_v^2.1.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'awilix-koa'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'awilix-koa' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'awilix-koa/lib/controller' {
  declare module.exports: any;
}

declare module 'awilix-koa/lib/index' {
  declare module.exports: any;
}

declare module 'awilix-koa/lib/invokers' {
  declare module.exports: any;
}

declare module 'awilix-koa/lib/scope-per-request' {
  declare module.exports: any;
}

// Filename aliases
declare module 'awilix-koa/lib/controller.js' {
  declare module.exports: $Exports<'awilix-koa/lib/controller'>;
}
declare module 'awilix-koa/lib/index.js' {
  declare module.exports: $Exports<'awilix-koa/lib/index'>;
}
declare module 'awilix-koa/lib/invokers.js' {
  declare module.exports: $Exports<'awilix-koa/lib/invokers'>;
}
declare module 'awilix-koa/lib/scope-per-request.js' {
  declare module.exports: $Exports<'awilix-koa/lib/scope-per-request'>;
}
