// flow-typed signature: c68efb21ea0510ae2b5d8bb3bc31283a
// flow-typed version: <<STUB>>/koa-methodoverride_v^2.0.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-methodoverride'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-methodoverride' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'koa-methodoverride/index' {
  declare module.exports: $Exports<'koa-methodoverride'>;
}
declare module 'koa-methodoverride/index.js' {
  declare module.exports: $Exports<'koa-methodoverride'>;
}
