// flow-typed signature: 3616aea9cc2c4a8ff1bcfc0e9f171dc2
// flow-typed version: <<STUB>>/linq_v^3.0.7/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'linq'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'linq' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'linq/extensions/linq.qunit' {
  declare module.exports: any;
}

declare module 'linq/linq' {
  declare module.exports: any;
}

declare module 'linq/linq.min' {
  declare module.exports: any;
}

declare module 'linq/minify' {
  declare module.exports: any;
}

declare module 'linq/sample/tutorial' {
  declare module.exports: any;
}

// Filename aliases
declare module 'linq/extensions/linq.qunit.js' {
  declare module.exports: $Exports<'linq/extensions/linq.qunit'>;
}
declare module 'linq/linq.js' {
  declare module.exports: $Exports<'linq/linq'>;
}
declare module 'linq/linq.min.js' {
  declare module.exports: $Exports<'linq/linq.min'>;
}
declare module 'linq/minify.js' {
  declare module.exports: $Exports<'linq/minify'>;
}
declare module 'linq/sample/tutorial.js' {
  declare module.exports: $Exports<'linq/sample/tutorial'>;
}
