// flow-typed signature: c50b6901291a4ef0dfd71223637f314b
// flow-typed version: <<STUB>>/structure_v^1.2.1/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'structure'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'structure' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'structure/dist/structure' {
  declare module.exports: any;
}

declare module 'structure/src/attributes/decorator' {
  declare module.exports: any;
}

declare module 'structure/src/attributes/descriptors' {
  declare module.exports: any;
}

declare module 'structure/src/attributes/index' {
  declare module.exports: any;
}

declare module 'structure/src/attributes/initialValuesCreation' {
  declare module.exports: any;
}

declare module 'structure/src/coercion/array' {
  declare module.exports: any;
}

declare module 'structure/src/coercion/boolean' {
  declare module.exports: any;
}

declare module 'structure/src/coercion/generic' {
  declare module.exports: any;
}

declare module 'structure/src/coercion/index' {
  declare module.exports: any;
}

declare module 'structure/src/coercion/number' {
  declare module.exports: any;
}

declare module 'structure/src/coercion/string' {
  declare module.exports: any;
}

declare module 'structure/src/errors' {
  declare module.exports: any;
}

declare module 'structure/src/index' {
  declare module.exports: any;
}

declare module 'structure/src/schema/index' {
  declare module.exports: any;
}

declare module 'structure/src/schema/normalization' {
  declare module.exports: any;
}

declare module 'structure/src/serialization/descriptor' {
  declare module.exports: any;
}

declare module 'structure/src/serialization/index' {
  declare module.exports: any;
}

declare module 'structure/src/serialization/serialize' {
  declare module.exports: any;
}

declare module 'structure/src/symbols' {
  declare module.exports: any;
}

declare module 'structure/src/typeDescriptor/index' {
  declare module.exports: any;
}

declare module 'structure/src/typeResolver' {
  declare module.exports: any;
}

declare module 'structure/src/validation/array' {
  declare module.exports: any;
}

declare module 'structure/src/validation/boolean' {
  declare module.exports: any;
}

declare module 'structure/src/validation/date' {
  declare module.exports: any;
}

declare module 'structure/src/validation/descriptors' {
  declare module.exports: any;
}

declare module 'structure/src/validation/index' {
  declare module.exports: any;
}

declare module 'structure/src/validation/nested' {
  declare module.exports: any;
}

declare module 'structure/src/validation/number' {
  declare module.exports: any;
}

declare module 'structure/src/validation/string' {
  declare module.exports: any;
}

declare module 'structure/src/validation/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'structure/dist/structure.js' {
  declare module.exports: $Exports<'structure/dist/structure'>;
}
declare module 'structure/src/attributes/decorator.js' {
  declare module.exports: $Exports<'structure/src/attributes/decorator'>;
}
declare module 'structure/src/attributes/descriptors.js' {
  declare module.exports: $Exports<'structure/src/attributes/descriptors'>;
}
declare module 'structure/src/attributes/index.js' {
  declare module.exports: $Exports<'structure/src/attributes/index'>;
}
declare module 'structure/src/attributes/initialValuesCreation.js' {
  declare module.exports: $Exports<'structure/src/attributes/initialValuesCreation'>;
}
declare module 'structure/src/coercion/array.js' {
  declare module.exports: $Exports<'structure/src/coercion/array'>;
}
declare module 'structure/src/coercion/boolean.js' {
  declare module.exports: $Exports<'structure/src/coercion/boolean'>;
}
declare module 'structure/src/coercion/generic.js' {
  declare module.exports: $Exports<'structure/src/coercion/generic'>;
}
declare module 'structure/src/coercion/index.js' {
  declare module.exports: $Exports<'structure/src/coercion/index'>;
}
declare module 'structure/src/coercion/number.js' {
  declare module.exports: $Exports<'structure/src/coercion/number'>;
}
declare module 'structure/src/coercion/string.js' {
  declare module.exports: $Exports<'structure/src/coercion/string'>;
}
declare module 'structure/src/errors.js' {
  declare module.exports: $Exports<'structure/src/errors'>;
}
declare module 'structure/src/index.js' {
  declare module.exports: $Exports<'structure/src/index'>;
}
declare module 'structure/src/schema/index.js' {
  declare module.exports: $Exports<'structure/src/schema/index'>;
}
declare module 'structure/src/schema/normalization.js' {
  declare module.exports: $Exports<'structure/src/schema/normalization'>;
}
declare module 'structure/src/serialization/descriptor.js' {
  declare module.exports: $Exports<'structure/src/serialization/descriptor'>;
}
declare module 'structure/src/serialization/index.js' {
  declare module.exports: $Exports<'structure/src/serialization/index'>;
}
declare module 'structure/src/serialization/serialize.js' {
  declare module.exports: $Exports<'structure/src/serialization/serialize'>;
}
declare module 'structure/src/symbols.js' {
  declare module.exports: $Exports<'structure/src/symbols'>;
}
declare module 'structure/src/typeDescriptor/index.js' {
  declare module.exports: $Exports<'structure/src/typeDescriptor/index'>;
}
declare module 'structure/src/typeResolver.js' {
  declare module.exports: $Exports<'structure/src/typeResolver'>;
}
declare module 'structure/src/validation/array.js' {
  declare module.exports: $Exports<'structure/src/validation/array'>;
}
declare module 'structure/src/validation/boolean.js' {
  declare module.exports: $Exports<'structure/src/validation/boolean'>;
}
declare module 'structure/src/validation/date.js' {
  declare module.exports: $Exports<'structure/src/validation/date'>;
}
declare module 'structure/src/validation/descriptors.js' {
  declare module.exports: $Exports<'structure/src/validation/descriptors'>;
}
declare module 'structure/src/validation/index.js' {
  declare module.exports: $Exports<'structure/src/validation/index'>;
}
declare module 'structure/src/validation/nested.js' {
  declare module.exports: $Exports<'structure/src/validation/nested'>;
}
declare module 'structure/src/validation/number.js' {
  declare module.exports: $Exports<'structure/src/validation/number'>;
}
declare module 'structure/src/validation/string.js' {
  declare module.exports: $Exports<'structure/src/validation/string'>;
}
declare module 'structure/src/validation/utils.js' {
  declare module.exports: $Exports<'structure/src/validation/utils'>;
}
